##################
# Global params
##################

# Subjects considered in analysis
subject_ids:
  - "001"
  #- "002"
  #- "003"

##################
# Step-specific params
##################

# Band-pass filter limits
filter:
  fmin: 0.6  # bandpass min frequency in Hz
  fmax: 50  # bandpass max frequency in Hz

cleanchannels:
  bad_channels: []

cleansegments:
  #strategy: "none"
  strategy: "manual"
  #strategy: "thresh"
  #strategy: "autoreject"
